Update validators.py
ugettext_lazy has been deprecated in django 3.0 ==> https://docs.djangoproject.com/en/4.0/releases/3.0/
and ugettext_lazy has been removed in django 4.0 ==> https://docs.djangoproject.com/en/4.0/releases/4.0/
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' 

ugettext_lazy has been replaced with gettext_lazy